// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsOpenFolder
{
    internal sealed partial class Vsix
    {
        public const string Id = "VsOpenFolder.8251f5ba-17b2-41db-94b8-e4c31740322c";
        public const string Name = "VsOpenFolder";
        public const string Description = @"Open output folder of active project in file explorer";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "1823411284237761";
        public const string Tags = "Vsix";
    }
}
